#spring 配置
spring:

  #redis配置
  redis:
    #数据库索引
    database: 0
    #redis 服务器地址
    host: localhost
    #redis 端口
    port: 6379
    #redis 密码 默认为空
    #password: 123456
    # 链接超时时间
    connect-timeout: 10s

    #lettuce连接池配置
    lettuce:
      pool:
        # 链接池中最小的空闲链接 默认为0
        min-idle: 0
        # 链接池中最大的空闲连接 默认为 8
        max-idle: 8
        #连接池中最大数据库链接数 默认为8
        max-active: 8
        #连接池最大阻塞等待时间 负值表示没有限制
        max-wait: -1ms


  # mysql 配置
  datasource:
    url: jdbc:mysql://localhost:3306/redis_like?characterEncoding=UTF8&serverTimezone=UTC&useSSL=false
    #用户名
    username: root
    #密码
    password: 123456
    # driver配置
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis配置
mybatis:

  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml